#!/bin/bash
n=500

if [[ "$#" -eq 1 ]]; then
	n=$1
fi

echo "Going Into Build Directory..."
cd build

echo CheBellaC0sa | sudo -S ./ConnectFour $n
./plot.py $n

echo "Exiting Build Directory..."
cd ..
